// eslint-disable-next-line no-unused-expressions
const options = [
   {
      id: 1,
      group: "front",
      level: 1,
      label:"FD junior",
      value:"front-end-junior",
   },
   {
      id: 2,
      group: "front",
      level: 2,
      label:"FD middle",
      value:"front-end-middle",
   },
   {
      id: 3,
      group: "front",
      level: 3,
      label:"FD senior",
      value:"front-end-senior",
   },
   {
      id: 4,
      group: "back",
      level: 1,
      label:"BD junior",
      value:"back-end-junior",
   },
   {
      id: 5,
      group: "back",
      level: 2,
      label:"BD middle",
      value:"back-end-middle",
   },
   {
      id: 6,
      group: "back",
      level: 3,
      label:"BD senior",
      value:"back-end-senior",
   },
   {
      id: 7,
      group: "qa",
      level: 1,
      label:"QA junior",
      value:"qa-junior",
   },
   {
      id: 8,
      group: "qa",
      level: 2,
      label:"QA middle",
      value:"qa-middle",
   },
   {
      id: 9,
      group: "qa",
      level: 3,
      label:"QA senior",
      value:"qa-senior",
   },
   {
      id: 10,
      group: "analyst",
      level: 1,
      label:"BA junior",
      value:"business-analyst-junior",
   },
   {
      id: 11,
      group: "analyst",
      level: 2,
      label:"BA middle",
      value:"business-analyst-middle",
   },
   {
      id: 12,
      group: "analyst",
      level: 3,
      label:"BA senior",
      value:"business-analyst-senior",
   },
   {
      id: 13,
      group: "ux-ui",
      level: 1,
      label:"UX/UI designer junior",
      value:"ux-ui-junior",
   },
   {
      id: 14,
      group: "ux-ui",
      level: 2,
      label:"UX/UI designer middle",
      value:"ux-ui-middle",
   },
   {
      id: 15,
      group: "ux-ui",
      level: 3,
      label:"UX/UI designer senior",
      value:"ux-ui-senior",
   },
   {
      id: 16,
      group: "marketing",
      level: 1,
      label:"MS junior",
      value:"marketing-specialist-junior",
   },
   {
      id: 17,
      group: "marketing",
      level: 2,
      label:"MS middle",
      value:"marketing-specialist-middle",
   },
   {
      id: 18,
      group: "marketing",
      level: 3,
      label:"MS senior",
      value:"marketing-specialist-senior",
   },
]

export default options;